@baseUrl = https://localhost:7006

### Local cache list (DB)
GET {{baseUrl}}/api/local/studies

### Sync a study from Orthanc into DB (replace ID)
POST {{baseUrl}}/api/local/studies/{{orthancStudyId}}/sync

### Get study from DB
GET {{baseUrl}}/api/local/studies/{{orthancStudyId}}

### Sync ALL studies from Orthanc into DB
POST {{baseUrl}}/api/local/studies/sync-all

### Import DICOM (multiple files)
POST {{Sitim.Api_HostAddress}}/api/studies/import
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="files"; filename="example.dcm"
Conent-Type: application/dicom

< ./path/to/example.dcm
------boundary--
