namespace Sitim.Core.Entities;

/// <summary>
/// Tracks one federated learning training session orchestrated across institutions.
/// </summary>
public sealed class FLSession
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Logical model identifier used by the FL pipeline
    /// </summary>
    public string ModelKey { get; set; } = string.Empty;

    public FLSessionStatus Status { get; set; } = FLSessionStatus.Pending;

    public int TotalRounds { get; set; } = 10;
    public int CurrentRound { get; set; }

    /// <summary>
    /// Optional external identifier from FL coordinator (Flower).
    /// </summary>
    public string? ExternalSessionId { get; set; }

    /// <summary>
    /// Optional path/key of trained model artifact (ONNX) generated by FL session.
    /// </summary>
    public string? OutputModelPath { get; set; }

    public string? LastError { get; set; }

    public Guid CreatedByUserId { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime? StartedAtUtc { get; set; }
    public DateTime? FinishedAtUtc { get; set; }

    public ICollection<FLRound> Rounds { get; set; } = new List<FLRound>();
    public ICollection<FLParticipant> Participants { get; set; } = new List<FLParticipant>();
}

public enum FLSessionStatus
{
    Pending = 0,
    Running = 1,
    Completed = 2,
    Failed = 3,
    Stopped = 4
}
