// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sitim.Infrastructure.Data;

#nullable disable

namespace Sitim.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210114206_MakePatientIdUnique")]
    partial class MakePatientIdUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sitim.Core.Entities.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("InputArchivePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("input_archive_path");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_key");

                    b.Property<string>("OrthancStudyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("orthanc_study_id");

                    b.Property<string>("OutputJsonPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("output_json_path");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("study_instance_uid");

                    b.HasKey("Id");

                    b.HasIndex("OrthancStudyId");

                    b.HasIndex("Status");

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("Sitim.Core.Entities.ImagingSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OrthancSeriesId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("orthanc_series_id");

                    b.Property<Guid>("StudyDbId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyDbId", "OrthancSeriesId")
                        .IsUnique();

                    b.ToTable("imaging_series", (string)null);
                });

            modelBuilder.Entity("Sitim.Core.Entities.ImagingStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.PrimitiveCollection<string[]>("ModalitiesInStudy")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("modalities_in_study");

                    b.Property<string>("OrthancStudyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("orthanc_study_id");

                    b.Property<Guid?>("PatientDbId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudyDate")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("study_date");

                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("study_instance_uid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OrthancStudyId")
                        .IsUnique();

                    b.HasIndex("PatientDbId");

                    b.HasIndex("StudyInstanceUid");

                    b.ToTable("imaging_studies", (string)null);
                });

            modelBuilder.Entity("Sitim.Core.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("PatientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Sitim.Core.Entities.ImagingSeries", b =>
                {
                    b.HasOne("Sitim.Core.Entities.ImagingStudy", "Study")
                        .WithMany("Series")
                        .HasForeignKey("StudyDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Sitim.Core.Entities.ImagingStudy", b =>
                {
                    b.HasOne("Sitim.Core.Entities.Patient", "Patient")
                        .WithMany("Studies")
                        .HasForeignKey("PatientDbId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Sitim.Core.Entities.ImagingStudy", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Sitim.Core.Entities.Patient", b =>
                {
                    b.Navigation("Studies");
                });
#pragma warning restore 612, 618
        }
    }
}
